import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "../globals.css";

import Sidebar from "@/components/Sidebar";
import { ThemeProviders } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import AppHeader from "@/components/AppHeader";
import GoogleMappProvider from "@/lib/GoogleMappProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "dark",
        inter.variable,
        "font-sans",
        geist.variable,
      )}
      data-theme="light"
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground">
        <ThemeProviders>
          <AppHeader />
          <div className="mt-16 flex h-[calc(100vh-64px)] overflow-y-hidden">
            <Sidebar />
            <main className="flex-1 p-4 overflow-y-auto">
              <GoogleMappProvider>{children}</GoogleMappProvider>
            </main>
          </div>
        </ThemeProviders>
      </body>
    </html>
  );
}
